project:
  type: website
  output-dir: docs
  resources:
    - "site_style.scss"
    - "resources"
website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  title: "Loïc Guezou"
  image: id.png
  favicon: id.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - href: education.qmd
        text: Education
      # - text: CV
      #   href: resources/CV.pdf
      #   target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
